### PR TITLE
Remove the PROD stage

### PR DESCRIPTION
**Pull request by akash1810**
## What does this change?
This project isn't quite ready to reach PROD. It is still a prototype. Remove the PROD stage to allow us to change the repository's topic from 'production' to 'prototype'.

A repository's topic signals what our approach to vulnerabilities should be; a 'prototype' doesn't need active monitoring/patching. Therefore the Snyk workflow is also removed.

Once merged, we'll need to manually:
- ~[ ] Delete the PROD CloudFormation stack~ @davidfurey has confirmed there isn't a PROD stack
- [x] Delete the project from Snyk

### CODE REVIEW

**Comment by davidfurey** [comment]
Looks good to me. Can I just check that you don't plan to keep a CODE version of this running either? Having unpatched software continually running in our AWS account poses a risk regardless of its stage.

**Comment by akash1810** [comment]
> Looks good to me. Can I just check that you don't plan to keep a CODE version of this running either? Having unpatched software continually running in our AWS account poses a risk regardless of its stage.

@dskamiotis and I will discuss what the future of this project should be in the next couple of weeks. We'll either remove CODE, or apply the patches and devise an LTS plan. WDYT?

**Comment by davidfurey** [comment]
That's fine with me.

**Comment by rhystmills** [comment]
It might be good to mention the demo-ness in the Readme so that future visitors are aware.

**Review by samanthagottlieb — APPROVED** [review]
Looks good to me.

**Comment by akash1810** [comment]
> It might be good to mention the prototype-ness in the Readme so that future visitors are aware.

Will do this separately.

**Comment by samanthagottlieb** [comment]
The project has now been deleted from Snyk.

**Pull request merged**
